server:
  port: 1111

spring:
    datasource:
        name: XUpdateService
        url: jdbc:mysql://localhost:3306/ota-boot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 1000MB
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 10MB
            max-request-size: 100MB
    mvc:
        view:
          prefix: classpath:/templates/
          suffix: .html

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.xuexiang.xupdateservice.model

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


upload:
  file-directory: ./uploads
  keep-name: true
